name: React_frontend
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: deploy to vm
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSH_KEY}}

          script: |
            cd /home/ubuntu/6weeks_ravina_Python
            git pull origin main
            sudo npm i 
            sudo npm run build
            pm2 restart "React_frontend" || pm2 start npm --name "React_frontend" -- run dev
          
